Cypress.Commands.add('movieHelper', () => {
    cy.get('a.image[title="Despicable Me 4"]').click()
    cy.get('#favourite').click()
    cy.get('div.nav_wrapper').find('a.logo').click({force: true})
    cy.wait(3000)
    cy.get('a.image[title="The Boy and the Heron"]').click()
    cy.get('#favourite').click()
    cy.get('div.nav_wrapper').find('a.logo').click({force: true})
    cy.wait(3000)
    })